# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names
file_template = %%rev%%_%%slug%%s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# installed by adding `alembic[tz]` to the pip requirements
# timezone = UTC

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the "describe()" command
# to get latest revision
# describe_revision = false

# version location specification; This defaults
# to alembic/versions.  When using a version root
# directory, the path is used as is
# version_locations = %(here)s/bar:%(here)s/bat

# version path separator; As mentioned above, it is ":" by default.
# If you want to use e.g. three-level directories,
# set this to "/", or "//" to use two slashes
# version_locations = "%(here)s/bar:%(here)s/bat"

# output encoding
# output_encoding = utf-8

sqlalchemy.url = %%DATABASE_URL%%s

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are called
# on newly generated revision scripts.  See the documentation for further
# detail on how to write a post_write_hook
# hook requires the use of the import hook feature
# hooks = alembic.tools.egg:hook

# interface to use when importing, if any. This interface
# will be used for any import hook, when defined here
# import_type = alembic.tools:Importhook

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s %(message)s
datefmt = %H:%M:%S